# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: smartshop.catalog::lang.categories.reorder_categories

# Attribute name
nameFrom: name

# Model Class name
modelClass: \SmartShop\Catalog\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar