# ===================================
#  Relation Behavior Config
# ===================================

values:
    deferredBinding: true
    label: smartshop.catalog::lang.property_value.label
    view:
        recordsPerPage: 10
        toolbarButtons: create|delete
        list: $/smartshop/catalog/models/property/values_columns.yaml
    manage:
        form: $/smartshop/catalog/models/property/values_fields.yaml