# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: smartshop.catalog::lang.import_template.label

# Model Form Field configuration
form: $/smartshop/catalog/models/importtemplate/fields.yaml

# Model Class name
modelClass: Smartshop\Catalog\Models\ImportTemplate

# Default redirect location
defaultRedirect: smartshop/catalog/importtemplates

# Create page
create:
    title: smartshop.catalog::lang.import_template.create_title
    redirect: smartshop/catalog/importtemplates/update/:id
    redirectClose: smartshop/catalog/importtemplates

# Update page
update:
    title: smartshop.catalog::lang.import_template.update_title
    redirect: smartshop/catalog/importtemplates
    redirectClose: smartshop/catalog/importtemplates

# Preview page
preview:
    title: smartshop.catalog::lang.import_template.preview_title