# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: smartshop.catalog::lang.product_property.label

# Model Form Field configuration
form: $/smartshop/catalog/models/productproperty/fields.yaml

# Model Class name
modelClass: Smartshop\Catalog\Models\ProductProperty

# Default redirect location
defaultRedirect: smartshop/catalog/productproperties

# Create page
create:
    title: smartshop.catalog::lang.product_property.create
    redirect: smartshop/catalog/productproperties/update/:id
    redirectClose: smartshop/catalog/productproperties

# Update page
update:
    title: smartshop.catalog::lang.product_property.update
    redirect: smartshop/catalog/productproperties
    redirectClose: smartshop/catalog/productproperties

# Preview page
preview:
    title: smartshop.catalog::lang.product_property.preview